/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apu.y2s1.pms.admin;

/**
 *
 * @author Thinkpad
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ModLecturersBtn = new javax.swing.JButton();
        ModStudentBtn1 = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("FUNCTION PAGE");
        Title.setToolTipText("");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 38, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLEASE SELECT AN ACTION YOU WANT TO CONTNUE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 97, -1, -1));

        ModLecturersBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ModLecturersBtn.setText("Modify Lecturers");
        ModLecturersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModLecturersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ModLecturersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 251, 210, 50));

        ModStudentBtn1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ModStudentBtn1.setText("Modify Students");
        ModStudentBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModStudentBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(ModStudentBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 156, 210, 50));

        LogOutBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 347, 210, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thinkpad\\Documents\\NetBeansProjects\\oodj\\pms\\src\\main\\java\\apu\\y2s1\\pms\\admin\\Img\\MenuBG.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -150, 880, 640));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/admin/Img/MenuBG.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModLecturersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModLecturersBtnActionPerformed
        apu.y2s1.pms.admin.ModLecturers add = new apu.y2s1.pms.admin.ModLecturers();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModLecturersBtnActionPerformed

    private void ModStudentBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModStudentBtn1ActionPerformed
        apu.y2s1.pms.admin.ModStudents add = new apu.y2s1.pms.admin.ModStudents();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModStudentBtn1ActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        apu.y2s1.pms.Login add = new apu.y2s1.pms.Login();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AdminMenu frame = new AdminMenu();
            frame.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton ModLecturersBtn;
    private javax.swing.JButton ModStudentBtn1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
