/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apu.y2s1.pms.admin;

/**
 *
 * @author Thinkpad
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        GenStatisticsBtn = new javax.swing.JButton();
        ModStudentBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        ModLecturersBtn1 = new javax.swing.JButton();
        ModPManagersBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("FUNCTION PAGE");
        Title.setToolTipText("");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLEASE SELECT AN ACTION YOU WANT TO CONTNUE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        GenStatisticsBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        GenStatisticsBtn.setText("Generate Statistics");
        GenStatisticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenStatisticsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(GenStatisticsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 210, 50));

        ModStudentBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ModStudentBtn.setText("Modify Students");
        ModStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ModStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 210, 50));

        LogOutBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 210, 50));

        ModLecturersBtn1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ModLecturersBtn1.setText("Modify Lecturers");
        ModLecturersBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModLecturersBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(ModLecturersBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 210, 50));

        ModPManagersBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ModPManagersBtn.setText("Modify Project Managers");
        ModPManagersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModPManagersBtnMouseClicked(evt);
            }
        });
        getContentPane().add(ModPManagersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 210, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/admin/Img/MenuBG.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -70, 1160, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenStatisticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenStatisticsBtnActionPerformed
        apu.y2s1.pms.admin.GenStatistics add = new apu.y2s1.pms.admin.GenStatistics();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_GenStatisticsBtnActionPerformed

    private void ModStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModStudentBtnActionPerformed
        apu.y2s1.pms.admin.ModStudents add = new apu.y2s1.pms.admin.ModStudents();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModStudentBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        apu.y2s1.pms.Login add = new apu.y2s1.pms.Login();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void ModLecturersBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModLecturersBtn1ActionPerformed
        apu.y2s1.pms.admin.ModLecturers add = new apu.y2s1.pms.admin.ModLecturers();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModLecturersBtn1ActionPerformed

    private void ModPManagersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModPManagersBtnMouseClicked
        apu.y2s1.pms.admin.ModPManagers add = new apu.y2s1.pms.admin.ModPManagers();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModPManagersBtnMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AdminMenu frame = new AdminMenu();
            frame.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenStatisticsBtn;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton ModLecturersBtn1;
    private javax.swing.JButton ModPManagersBtn;
    private javax.swing.JButton ModStudentBtn;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
