/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.admin;

import apu.y2s1.pms.DataAbstract;

/**
 *
 * @author Thinkpad
 */
public class GenStatistics extends javax.swing.JFrame {
    
    /**
     * Creates new form GenStatistics
     */
    public GenStatistics() {
        initComponents();
        GenTotalStudNumMouseClicked(null);
        GenTotalLectNumMouseClicked(null);
        GenTotalAdmNumMouseClicked(null);
        GenTotalPManagerNumMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StudentAmt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LectAmt = new javax.swing.JTextField();
        GenTotalStudNum = new javax.swing.JButton();
        ReportAmt = new javax.swing.JTextField();
        GenTotalLectNum = new javax.swing.JButton();
        GenTotalGRepNum = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        TopBG = new javax.swing.JTextField();
        GenTotalAdmNum = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        StaffAmt = new javax.swing.JTextField();
        Status = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        PManagerAmt = new javax.swing.JTextField();
        GenTotalPManagerNum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel1.setText("Total Number of Students:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));
        getContentPane().add(StudentAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 99, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel3.setText("Total Number of Project Managers:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));
        getContentPane().add(LectAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 99, -1));

        GenTotalStudNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalStudNum.setText("Generate");
        GenTotalStudNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalStudNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalStudNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));
        getContentPane().add(ReportAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 99, -1));

        GenTotalLectNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalLectNum.setText("Generate");
        GenTotalLectNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalLectNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalLectNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        GenTotalGRepNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalGRepNum.setText("Generate");
        GenTotalGRepNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalGRepNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalGRepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel4.setText("Total Number of Reports:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, 30));

        HomeBtn.setBackground(new java.awt.Color(153, 204, 255));
        HomeBtn.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        HomeBtn.setText("HOME");
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        Title.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title.setText("GENERATE STATISTICS");
        Title.setToolTipText("");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 40));

        TopBG.setBackground(new java.awt.Color(153, 204, 255));
        TopBG.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(TopBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        GenTotalAdmNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalAdmNum.setText("Generate");
        GenTotalAdmNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalAdmNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalAdmNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel5.setText("Total Number of Administrators:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, 40));
        getContentPane().add(StaffAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 99, -1));

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graded", "Submitted", "Processing" }));
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel6.setText("Total Number of Lecturers:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));
        getContentPane().add(PManagerAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 99, -1));

        GenTotalPManagerNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalPManagerNum.setText("Generate");
        GenTotalPManagerNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalPManagerNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalPManagerNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/admin/Img/AdminFnBG.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1030, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenTotalStudNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalStudNumMouseClicked
        int count;
        DataAbstract db = new DataAbstract("Students.txt");
        if ((count = db.countLines()) != -1){
            StudentAmt.setText(Integer.toString(count));
        } else {
            StudentAmt.setText("Error");
        }
    }//GEN-LAST:event_GenTotalStudNumMouseClicked

    private void GenTotalLectNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalLectNumMouseClicked
        int count;
        DataAbstract db = new DataAbstract("Lecturers.txt");
        if ((count = db.countLines()) != -1){
            LectAmt.setText(Integer.toString(count));
        } else {
            LectAmt.setText("Error");
        }
    }//GEN-LAST:event_GenTotalLectNumMouseClicked

    private void GenTotalGRepNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalGRepNumMouseClicked
        ReportAmt.setText("Calculating...");
        DataAbstract db = new DataAbstract("Submissions.txt");
        ReportAmt.setText(Integer.toString(db.getSearchCount(Status.getSelectedItem().toString())));
    }//GEN-LAST:event_GenTotalGRepNumMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        apu.y2s1.pms.admin.AdminMenu add = new apu.y2s1.pms.admin.AdminMenu();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void GenTotalAdmNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalAdmNumMouseClicked
        int count;
        DataAbstract db = new DataAbstract("Admins.txt");
        if ((count = db.countLines()) != -1){
            StaffAmt.setText(Integer.toString(count));
        } else {
            StaffAmt.setText("Error");
        }
    }//GEN-LAST:event_GenTotalAdmNumMouseClicked

    private void GenTotalPManagerNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalPManagerNumMouseClicked
        int count;
        DataAbstract db = new DataAbstract("ProjectManagers.txt");
        if ((count = db.countLines()) != -1){
            PManagerAmt.setText(Integer.toString(count));
        } else {
            PManagerAmt.setText("Error");
        }
    }//GEN-LAST:event_GenTotalPManagerNumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenTotalAdmNum;
    private javax.swing.JButton GenTotalGRepNum;
    private javax.swing.JButton GenTotalLectNum;
    private javax.swing.JButton GenTotalPManagerNum;
    private javax.swing.JButton GenTotalStudNum;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JTextField LectAmt;
    private javax.swing.JTextField PManagerAmt;
    private javax.swing.JTextField ReportAmt;
    private javax.swing.JTextField StaffAmt;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JTextField StudentAmt;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TopBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
