/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.admin;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Thinkpad
 */
public class GenStatistics extends javax.swing.JFrame {

    /**
     * Creates new form GenStatistics
     */
    public GenStatistics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StudentAmt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TrainerAmt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        StaffAmt = new javax.swing.JTextField();
        GenTotalStudNum = new javax.swing.JButton();
        GenTotalLectNum = new javax.swing.JButton();
        GenTotalAdmNum = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        TopBG = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel1.setText("Total Number of Students:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));
        getContentPane().add(StudentAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 99, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel3.setText("Total Number of Lecturers:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));
        getContentPane().add(TrainerAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 99, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel4.setText("Total Number of  Administrators:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 30));
        getContentPane().add(StaffAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 99, -1));

        GenTotalStudNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalStudNum.setText("Generate");
        GenTotalStudNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalStudNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalStudNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        GenTotalLectNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalLectNum.setText("Generate");
        GenTotalLectNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalLectNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalLectNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        GenTotalAdmNum.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        GenTotalAdmNum.setText("Generate");
        GenTotalAdmNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenTotalAdmNumMouseClicked(evt);
            }
        });
        getContentPane().add(GenTotalAdmNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        HomeBtn.setBackground(new java.awt.Color(153, 204, 255));
        HomeBtn.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        HomeBtn.setText("HOME");
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        Title.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title.setText("MODIFY STUDENTS");
        Title.setToolTipText("");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 40));

        TopBG.setBackground(new java.awt.Color(153, 204, 255));
        TopBG.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(TopBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenTotalStudNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalStudNumMouseClicked
        Integer linelen = 0;

        String filePath = "Student.txt";
        File file = new File(filePath);

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            while (reader.readLine() != null) {
                linelen++;
            }
            String len = Integer.toString(linelen);

            StudentAmt.setText(len);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GenTotalStudNumMouseClicked

    private void GenTotalLectNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalLectNumMouseClicked
        Integer linelen = 0;

        String filePath = "Lecturer.txt";
        File file = new File(filePath);

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            while (reader.readLine() != null) {
                linelen++;
            }
            String len = Integer.toString(linelen);

            TrainerAmt.setText(len);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GenTotalLectNumMouseClicked

    private void GenTotalAdmNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenTotalAdmNumMouseClicked
        Integer linelen = 0;

        String filePath = "StaffData.txt";
        File file = new File(filePath);

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            while (reader.readLine() != null) {
                linelen++;
            }
            String len = Integer.toString(linelen);

            StaffAmt.setText(len);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GenTotalAdmNumMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        apu.y2s1.pms.admin.AdminMenu add = new apu.y2s1.pms.admin.AdminMenu();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenTotalAdmNum;
    private javax.swing.JButton GenTotalLectNum;
    private javax.swing.JButton GenTotalStudNum;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JTextField StaffAmt;
    private javax.swing.JTextField StudentAmt;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TopBG;
    private javax.swing.JTextField TrainerAmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
