/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.admin;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Thinkpad
 */
public class ModPManagers extends javax.swing.JFrame {

    /**
     * Creates new form ModPManagers
     */
    public ModPManagers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeBtn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        TopBG = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PMPwd = new javax.swing.JPasswordField();
        EditBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        SearchTxt = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PMTable = new javax.swing.JTable();
        RefBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeBtn.setBackground(new java.awt.Color(153, 204, 255));
        HomeBtn.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        HomeBtn.setText("HOME");
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        Title.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title.setText("MODIFY PROJECT MANAGERS");
        Title.setToolTipText("");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 40));

        TopBG.setBackground(new java.awt.Color(153, 204, 255));
        TopBG.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(TopBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel1.setText("Edit Project Manager Details:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel3.setText("Project Manager ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));
        getContentPane().add(PID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel4.setText("Lecturer ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        LID.setEditable(false);
        getContentPane().add(LID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel5.setText("Project Manager Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));
        getContentPane().add(PMPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 99, -1));

        EditBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        EditBtn.setText("Edit");
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        getContentPane().add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 70, -1));

        DelBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        DelBtn.setText("Delete");
        DelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(DelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        SearchTxt.setText("PM000");
        getContentPane().add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, 30));

        SearchBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        ResetBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        getContentPane().add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        PMTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TP Number", "Name", "Email", "Password", "Intake"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PMTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 402, 614, 220));

        RefBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        RefBtn.setText("Refresh");
        RefBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefBtnMouseClicked(evt);
            }
        });
        getContentPane().add(RefBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/admin/Img/AdminFnBG.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1030, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        apu.y2s1.pms.admin.AdminMenu add = new apu.y2s1.pms.admin.AdminMenu();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) PMTable.getModel();
        if (PMTable.getSelectedRowCount()==1) {
            String pid = PID.getText();
            String lid = LID.getText();
            char[] pwd = PMPwd.getPassword();

            model.setValueAt(pid, PMTable.getSelectedRow(),0);
            model.setValueAt(lid, PMTable.getSelectedRow(),1);
            model.setValueAt(pwd, PMTable.getSelectedRow(),2);

            JOptionPane.showMessageDialog(this, "Project Manager Details have been edited succesfully!");
            Save(model);
        }

        else {
            JOptionPane.showMessageDialog(this, "Please select the column you wish to edit before typing.");
        }
    }//GEN-LAST:event_EditBtnMouseClicked

    private void DelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) PMTable.getModel();
        if (PMTable.getSelectedRowCount()==1) {
            String pid = PID.getText();
            String lid = LID.getText();
            char[] pwd = PMPwd.getPassword();

            model.setValueAt(pid, PMTable.getSelectedRow(),0);
            model.setValueAt(lid, PMTable.getSelectedRow(),1);
            model.setValueAt(pwd, PMTable.getSelectedRow(),2);

            model.removeRow(PMTable.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Project Manager Details have been deleted succesfully!");
            Save(model);
        }
    }//GEN-LAST:event_DelBtnMouseClicked

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) PMTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        PMTable.setRowSorter(sorter);
        String search = SearchTxt.getText();
        sorter.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) PMTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        PMTable.setRowSorter(sorter);
        String search = "";
        sorter.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void RefBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefBtnMouseClicked
        String filePath = "ProjectManagers.txt";
        File file = new File(filePath);

        try {
            BufferedReader buffer = new BufferedReader(new FileReader(file));

            DefaultTableModel model = (DefaultTableModel) PMTable.getModel();
            model.setRowCount(0);

            String line;
            while ((line = buffer.readLine()) != null) {
                String[] data = line.split(";");
                model.addRow(data);
            }
            buffer.close();
        } catch (IOException ex) {
            Logger.getLogger(ModStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModPManagers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModPManagers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModPManagers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModPManagers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModPManagers().setVisible(true);
            }
        });
    }
    
    private void Save(DefaultTableModel model) {
       try {
           BufferedWriter writer = new BufferedWriter(new FileWriter("ProjectManagers.txt"));
           
           for (int row = 0; row < model.getRowCount(); row++) {
               for (int col = 0; col < model.getColumnCount(); col++) {
                   Object cellValue = model.getValueAt(row, col);
                   if (cellValue != null) {
                       String cellString = cellValue.toString();
                       writer.write(cellString);
                   }
                   if (col < model.getColumnCount() - 1) {
                       writer.write(";");
                   }
               }
               writer.newLine();
                   }
           writer.close();
       } catch (IOException e) {
           e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JTextField LID;
    private javax.swing.JTextField PID;
    private javax.swing.JPasswordField PMPwd;
    private javax.swing.JTable PMTable;
    private javax.swing.JButton RefBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TopBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
