/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apu.y2s1.pms.admin;

import apu.y2s1.pms.DataAbstract;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Thinkpad
 */
public class ModStudents extends javax.swing.JFrame {

    /**
     * Creates new form NewJDialog
     */
    public ModStudents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        STable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        SPwd = new javax.swing.JPasswordField();
        AddBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        SearchTxt = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        RefBtn = new javax.swing.JButton();
        SelectFile = new javax.swing.JButton();
        SelFilePath = new javax.swing.JTextField();
        HomeBtn = new javax.swing.JButton();
        TopBG = new javax.swing.JTextField();
        AddFileBtn = new javax.swing.JButton();
        SIntake = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Title.setText("MODIFY STUDENTS");
        Title.setToolTipText("");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 40));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel1.setText("Individual New Student:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel2.setText("Intake List Text File:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel3.setText("TP Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        getContentPane().add(TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 99, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel4.setText("Student Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
        getContentPane().add(SName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 128, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel7.setText("Student Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));
        getContentPane().add(SEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 128, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel5.setText("Student Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        STable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TP Number", "Name", "Password", "Email", "Intake"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(STable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 410, 880, 200));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel6.setText("Intake Code:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));
        getContentPane().add(SPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 99, -1));

        AddBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        getContentPane().add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 55, -1));

        EditBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        EditBtn.setText("Edit");
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        getContentPane().add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 70, -1));

        DelBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        DelBtn.setText("Delete");
        DelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(DelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        SearchTxt.setText("TP000");
        getContentPane().add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 30));

        SearchBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        ResetBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        getContentPane().add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        RefBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        RefBtn.setText("Refresh");
        RefBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefBtnMouseClicked(evt);
            }
        });
        getContentPane().add(RefBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, -1, -1));

        SelectFile.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        SelectFile.setText("Select File");
        SelectFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectFileMouseClicked(evt);
            }
        });
        getContentPane().add(SelectFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));
        getContentPane().add(SelFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 269, -1));

        HomeBtn.setBackground(new java.awt.Color(153, 204, 255));
        HomeBtn.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        HomeBtn.setText("HOME");
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        TopBG.setBackground(new java.awt.Color(153, 204, 255));
        TopBG.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(TopBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        AddFileBtn.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        AddFileBtn.setText("Add File");
        AddFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddFileBtnMouseClicked(evt);
            }
        });
        getContentPane().add(AddFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));
        getContentPane().add(SIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 80, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/admin/Img/AdminFnBG.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1030, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        String tp = TP.getText();
        String name = SName.getText();
        String email = SEmail.getText();
        char[] pwd = SPwd.getPassword();
        String pass = new String(pwd);
        String intake = SIntake.getText();

        if (tp.isEmpty() || name.isEmpty() || email.isEmpty() || pwd.length==0 || intake.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error! Please ensure that all text fields are not empty.");
            return;
        }

        try {
            FileWriter file = new FileWriter("Students.txt", true);
            BufferedWriter writer = new BufferedWriter(file);

            writer.write(tp + ";" + name + ";" + email + ";" + pass + ";" + intake + ";" + "\n");
            writer.close();
            JOptionPane.showMessageDialog(null,"New Student user has successfully been added!");
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) STable.getModel();
        if (STable.getSelectedRowCount()==1) {
            String tp = TP.getText();
            String name = SName.getText();
            String email = SEmail.getText();
            char[] pwd = SPwd.getPassword();
            String intake = SIntake.getText();

            model.setValueAt(tp, STable.getSelectedRow(),0);
            model.setValueAt(name, STable.getSelectedRow(),1);
            model.setValueAt(email, STable.getSelectedRow(),2);
            model.setValueAt(pwd, STable.getSelectedRow(),3);
            model.setValueAt(intake, STable.getSelectedRow(),4);

            JOptionPane.showMessageDialog(this, "Student Details have been edited succesfully!");
            Save(model);
        }

        else {
            JOptionPane.showMessageDialog(this, "Please select the column you wish to edit before typing.");
        }
    }//GEN-LAST:event_EditBtnMouseClicked

    private void DelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) STable.getModel();
        if (STable.getSelectedRowCount()==1) {
            String tp = TP.getText();
            String name = SName.getText();
            String email = SEmail.getText();
            char[] pwd = SPwd.getPassword();
            String intake = SIntake.getText();

            model.setValueAt(tp, STable.getSelectedRow(),0);
            model.setValueAt(name, STable.getSelectedRow(),1);
            model.setValueAt(email, STable.getSelectedRow(),2);
            model.setValueAt(pwd, STable.getSelectedRow(),3);
            model.setValueAt(intake, STable.getSelectedRow(),4);

            model.removeRow(STable.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Student Details have been deleted succesfully!");
            Save(model);
        }
    }//GEN-LAST:event_DelBtnMouseClicked

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) STable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        STable.setRowSorter(sorter);
        String search = SearchTxt.getText();
        sorter.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) STable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        STable.setRowSorter(sorter);
        String search = "";
        sorter.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void RefBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefBtnMouseClicked
        String filePath = "Students.txt";
        File file = new File(filePath);

        try {
            BufferedReader buffer = new BufferedReader(new FileReader(file));

            DefaultTableModel model = (DefaultTableModel) STable.getModel();
            model.setRowCount(0);

            String line;
            while ((line = buffer.readLine()) != null) {
                String[] data = line.split(";");
                model.addRow(data);
            }
            buffer.close();
        } catch (IOException ex) {
            Logger.getLogger(ModStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefBtnMouseClicked

    private void SelectFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectFileMouseClicked
        JFileChooser fchooser = new JFileChooser();
        fchooser.showOpenDialog(null);
        File f = fchooser.getSelectedFile();
        String fname = f.getAbsolutePath();
        SelFilePath.setText(fname); 
    }//GEN-LAST:event_SelectFileMouseClicked

    private void AddFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFileBtnMouseClicked
        DataAbstract fRead = new DataAbstract(SelFilePath.getText());
        DataAbstract fDB = new DataAbstract("Lecturers.txt");
        List<String[]> fReadRows = fRead.getAllRows();
        for(String[] row: fReadRows){
            fDB.writeTo(row);
        }
    }//GEN-LAST:event_AddFileBtnMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        apu.y2s1.pms.admin.AdminMenu add = new apu.y2s1.pms.admin.AdminMenu();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModStudents frame = new ModStudents();
                frame.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                frame.setVisible(true);
            }
        });
    }
    
    private void Save(DefaultTableModel model) {
       try {
           BufferedWriter writer = new BufferedWriter(new FileWriter("Students.txt"));
           
           for (int row = 0; row < model.getRowCount(); row++) {
               for (int col = 0; col < model.getColumnCount(); col++) {
                   Object cellValue = model.getValueAt(row, col);
                   if (cellValue != null) {
                       String cellString = cellValue.toString();
                       writer.write(cellString);
                   }
                   if (col < model.getColumnCount() - 1) {
                       writer.write(";");
                   }
               }
               writer.newLine();
                   }
           writer.close();
       } catch (IOException e) {
           e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton AddFileBtn;
    private javax.swing.JButton DelBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton RefBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JTextField SEmail;
    private javax.swing.JTextField SIntake;
    private javax.swing.JTextField SName;
    private javax.swing.JPasswordField SPwd;
    private javax.swing.JTable STable;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JTextField SelFilePath;
    private javax.swing.JButton SelectFile;
    private javax.swing.JTextField TP;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TopBG;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
