/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.projects;

import java.util.ArrayList;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import apu.y2s1.pms.DataAbstract;

/**
 *
 * @author tenen
 */
public class TableViewWindow extends javax.swing.JFrame {

    /**
     * Creates new form TableViewWindow
     */
    public TableViewWindow(String mode) {
        initComponents();
        switch(mode){
            case "allSubs":
                jLabel1.setText("All Submissions");
                showAllSubs();
                break;
            case "allPres":
                jLabel1.setText("All Presentation Schedules");
                showAllPres();
                break;
            case "allAsss":
                jLabel1.setText("All Assessments");
                showAllAsss();
                break;
            case "allSupervisees":
                jLabel1.setText("All Supervisees");
                showAllSupervisees();
                break;
            case "allSupervisors":
                jLabel1.setText("All Supervisors");
                showAllSupervisors();
                break;
            default:
                jLabel1.setText("All Lecturers");
                showAllLecturers();
                break;
        }
    }

    public TableViewWindow() {
        javax.swing.JOptionPane.showMessageDialog(null,"Please provide at least one parameter to the constructor.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 2, 24)); // NOI18N
        jLabel1.setText("<placeholder>");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setText("Table View:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void showAllSubs(){
        String filename = "Submissions.txt";
        int[] desiredColumns = {0, 1, 2, 3, 6, 7, 8, 11, 12, 13};
        String colNames[] = {"Submission ID", "Student TP", "Assessment ID", "Submission Timestamp", "Status", "Result", "Feedback", "Request Extension days", "New Due Date", "Moodle Link" };
        load_table(filename, desiredColumns, colNames);
    }

    private void showAllPres(){
        String filename = "Submissions.txt";
        int[] desiredColumns = {0, 1, 2, 4, 5};
        String colNames[] = {"Assessment ID", "Student TP", "Assessment ID", "Presentation Date", "Presentation Status"};
        load_table(filename, desiredColumns, colNames);
    }

    private void showAllAsss(){
        String filename = "Assessments.txt";
        int[] desiredColumns = {0, 1, 2, 3, 6, 7};
        String colNames[] = {"Assessment ID", "Name", "Type", "Supervisor", "Hand Out Date", "Due Date"};
        load_table(filename, desiredColumns, colNames);
    }

    private void showAllSupervisees(){
        String filename = "Students.txt";
        int[] desiredColumns = {0, 1, 4, 5};
        String colNames[] = {"Student TP", "Name", "Intake Code", "Assessment ID"};
        load_table(filename, desiredColumns, colNames);
    } 

    private void showAllSupervisors(){
        String filename = "Assessments.txt";
        int[] desiredColumns = {0, 1, 3};
        String colNames[] = {"Assessment ID", "Name", "Supervisor"};
        load_table(filename, desiredColumns, colNames);
    }

    private void showAllLecturers(){
        String filename = "Lecturers.txt";
        int[] desiredColumns = {0, 1, 3};
        String colNames[] = {"ID Number", "Name", "Email"};
        load_table(filename, desiredColumns, colNames);
    }

    private void load_table(String filename, int[] desiredColumns, String[] colNames){ 
        DataAbstract db = new DataAbstract(filename);
        List<String[]> db_list = db.getAllRows();

        // Create a new list to store the desired columns
        List<String[]> desiredData = new ArrayList<>();

        // Iterate over each row in db_list and extract the desired columns
        for (String[] row : db_list) {
            String[] desiredRow = new String[desiredColumns.length];
            for (int i = 0; i < desiredColumns.length; i++) {
                desiredRow[i] = row[desiredColumns[i]];
            }
            desiredData.add(desiredRow);
        }

        // Populate jTable1 with the desired data
        DefaultTableModel tableModel = new DefaultTableModel(colNames, 0);
        for (String[] row : desiredData) {
            tableModel.addRow(row);
        }
        jTable1.setModel(tableModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableViewWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
