/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.lecturer;

import apu.y2s1.pms.projects.TableViewWindow;

/**
 *
 * @author Jeslyn
 */
public class LecturerMenu extends javax.swing.JFrame {
    Lecturer thisLec;

    /**
     * Creates new form LecturerMenu
     */
    public LecturerMenu() {
        thisLec = (Lecturer) Lecturer.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SecondMarking = new javax.swing.JButton();
        FirstMarking = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        ViewMarkFeedback = new javax.swing.JButton();
        CfmPresentReq = new javax.swing.JButton();
        viewSubsBtn = new javax.swing.JButton();
        viewAsssBtn = new javax.swing.JButton();
        viewPresentSlots = new javax.swing.JButton();
        viewSupervisees = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        Title.setText("FUNCTION PAGE");
        Title.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel1.setText("PLEASE SELECT AN ACTION YOU WANT TO CONTINUE:");

        SecondMarking.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        SecondMarking.setText("Second Marking");
        SecondMarking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondMarkingActionPerformed(evt);
            }
        });

        FirstMarking.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        FirstMarking.setText("First Marking");
        FirstMarking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstMarkingActionPerformed(evt);
            }
        });

        LogOutBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        ViewMarkFeedback.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ViewMarkFeedback.setText("View Marking Feedback");
        ViewMarkFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMarkFeedbackActionPerformed(evt);
            }
        });

        CfmPresentReq.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        CfmPresentReq.setText("Confirm Presentation Request");
        CfmPresentReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CfmPresentReqActionPerformed(evt);
            }
        });

        viewSubsBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewSubsBtn.setText("View All Submissions");
        viewSubsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSubsBtnActionPerformed(evt);
            }
        });

        viewAsssBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewAsssBtn.setText("View All Assessments");
        viewAsssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAsssBtnActionPerformed(evt);
            }
        });

        viewPresentSlots.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewPresentSlots.setText("View Presentation Request");
        viewPresentSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPresentSlotsActionPerformed(evt);
            }
        });

        viewSupervisees.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewSupervisees.setText("View Supervisees");
        viewSupervisees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSuperviseesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 147, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewPresentSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CfmPresentReq, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewMarkFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FirstMarking, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SecondMarking, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewSubsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewAsssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewSupervisees, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Title)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSubsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAsssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSupervisees, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstMarking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondMarking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewMarkFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPresentSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CfmPresentReq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SecondMarkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondMarkingActionPerformed
        MarkingWindow secondMark = new MarkingWindow("2");
        secondMark.setVisible(true);
    }//GEN-LAST:event_SecondMarkingActionPerformed

    private void FirstMarkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstMarkingActionPerformed
        MarkingWindow firstMark = new MarkingWindow("1");
        firstMark.setVisible(true);
    }//GEN-LAST:event_FirstMarkingActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        apu.y2s1.pms.Login add = new apu.y2s1.pms.Login();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void ViewMarkFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMarkFeedbackActionPerformed
        ViewFeedbackWindow fbwin = new ViewFeedbackWindow();
        fbwin.setVisible(true);
    }//GEN-LAST:event_ViewMarkFeedbackActionPerformed

    private void CfmPresentReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CfmPresentReqActionPerformed
        ReqConfirmWindow rqcfm = new ReqConfirmWindow();
        rqcfm.setVisible(true);
    }//GEN-LAST:event_CfmPresentReqActionPerformed

    private void viewSubsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSubsBtnActionPerformed
        apu.y2s1.pms.projects.TableViewWindow viewSubs = new TableViewWindow("allSubs");
        viewSubs.setVisible(true);
    }//GEN-LAST:event_viewSubsBtnActionPerformed

    private void viewAsssBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAsssBtnActionPerformed
        apu.y2s1.pms.projects.TableViewWindow viewAsss = new TableViewWindow("allAsss");
        viewAsss.setVisible(true);
    }//GEN-LAST:event_viewAsssBtnActionPerformed

    private void viewPresentSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPresentSlotsActionPerformed
        apu.y2s1.pms.projects.TableViewWindow presentSlotTable = new TableViewWindow("allPres");
        presentSlotTable.setVisible(true);
    }//GEN-LAST:event_viewPresentSlotsActionPerformed

    private void viewSuperviseesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSuperviseesActionPerformed
        apu.y2s1.pms.projects.TableViewWindow supervisees = new TableViewWindow("allSupervisees");
        supervisees.setVisible(true);
    }//GEN-LAST:event_viewSuperviseesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CfmPresentReq;
    private javax.swing.JButton FirstMarking;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton SecondMarking;
    private javax.swing.JLabel Title;
    private javax.swing.JButton ViewMarkFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewAsssBtn;
    private javax.swing.JButton viewPresentSlots;
    private javax.swing.JButton viewSubsBtn;
    private javax.swing.JButton viewSupervisees;
    // End of variables declaration//GEN-END:variables
}
