/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.lecturer;

import apu.y2s1.pms.projects.TableViewWindow;

/**
 *
 * @author Jeslyn
 */
public class LecturerMenu extends javax.swing.JFrame {
    Lecturer thisLec;

    /**
     * Creates new form LecturerMenu
     */
    public LecturerMenu() {
        thisLec = (Lecturer) Lecturer.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SecondMarking = new javax.swing.JButton();
        FirstMarking = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        ViewMarkFeedback = new javax.swing.JButton();
        CfmPresentReq = new javax.swing.JButton();
        viewSubsBtn = new javax.swing.JButton();
        viewAsssBtn = new javax.swing.JButton();
        viewPresentSlots = new javax.swing.JButton();
        viewSupervisees = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        Title.setText("FUNCTION PAGE");
        Title.setToolTipText("");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 43, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel1.setText("PLEASE SELECT AN ACTION YOU WANT TO CONTINUE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 102, -1, -1));

        SecondMarking.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        SecondMarking.setText("Second Marking");
        SecondMarking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondMarkingActionPerformed(evt);
            }
        });
        getContentPane().add(SecondMarking, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 210, 50));

        FirstMarking.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        FirstMarking.setText("First Marking");
        FirstMarking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstMarkingActionPerformed(evt);
            }
        });
        getContentPane().add(FirstMarking, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 210, 50));

        LogOutBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 210, 50));

        ViewMarkFeedback.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ViewMarkFeedback.setText("View Marking Feedback");
        ViewMarkFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMarkFeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(ViewMarkFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, 50));

        CfmPresentReq.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        CfmPresentReq.setText("Confirm Presentation Request");
        CfmPresentReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CfmPresentReqActionPerformed(evt);
            }
        });
        getContentPane().add(CfmPresentReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, 50));

        viewSubsBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewSubsBtn.setText("View All Submissions");
        viewSubsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSubsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewSubsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 210, 50));

        viewAsssBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewAsssBtn.setText("View All Assessments");
        viewAsssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAsssBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewAsssBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 210, 50));

        viewPresentSlots.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewPresentSlots.setText("View Presentation Request");
        viewPresentSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPresentSlotsActionPerformed(evt);
            }
        });
        getContentPane().add(viewPresentSlots, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 210, 50));

        viewSupervisees.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        viewSupervisees.setText("View Supervisees");
        viewSupervisees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSuperviseesActionPerformed(evt);
            }
        });
        getContentPane().add(viewSupervisees, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 210, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SecondMarkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondMarkingActionPerformed
        MarkingWindow secondMark = new MarkingWindow("2");
        //secondMark.setVisible(true);
    }//GEN-LAST:event_SecondMarkingActionPerformed

    private void FirstMarkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstMarkingActionPerformed
        MarkingWindow firstMark = new MarkingWindow("1");
        //firstMark.setVisible(true);
    }//GEN-LAST:event_FirstMarkingActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        apu.y2s1.pms.Login add = new apu.y2s1.pms.Login();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void ViewMarkFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMarkFeedbackActionPerformed
        ViewFeedbackWindow fbwin = new ViewFeedbackWindow();
        fbwin.setVisible(true);
    }//GEN-LAST:event_ViewMarkFeedbackActionPerformed

    private void CfmPresentReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CfmPresentReqActionPerformed
        ReqConfirmWindow rqcfm = new ReqConfirmWindow();
        rqcfm.setVisible(true);
    }//GEN-LAST:event_CfmPresentReqActionPerformed

    private void viewSubsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSubsBtnActionPerformed
        apu.y2s1.pms.projects.TableViewWindow viewSubs = new TableViewWindow("allSubs");
        viewSubs.setVisible(true);
    }//GEN-LAST:event_viewSubsBtnActionPerformed

    private void viewAsssBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAsssBtnActionPerformed
        apu.y2s1.pms.projects.TableViewWindow viewAsss = new TableViewWindow("allAsss");
        viewAsss.setVisible(true);
    }//GEN-LAST:event_viewAsssBtnActionPerformed

    private void viewPresentSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPresentSlotsActionPerformed
        apu.y2s1.pms.projects.TableViewWindow presentSlotTable = new TableViewWindow("allPres");
        presentSlotTable.setVisible(true);
    }//GEN-LAST:event_viewPresentSlotsActionPerformed

    private void viewSuperviseesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSuperviseesActionPerformed
        apu.y2s1.pms.projects.TableViewWindow supervisees = new TableViewWindow("allSupervisees");
        supervisees.setVisible(true);
    }//GEN-LAST:event_viewSuperviseesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CfmPresentReq;
    private javax.swing.JButton FirstMarking;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton SecondMarking;
    private javax.swing.JLabel Title;
    private javax.swing.JButton ViewMarkFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewAsssBtn;
    private javax.swing.JButton viewPresentSlots;
    private javax.swing.JButton viewSubsBtn;
    private javax.swing.JButton viewSupervisees;
    // End of variables declaration//GEN-END:variables
}
