/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.student;

import apu.y2s1.pms.User;
import apu.y2s1.pms.DataAbstract;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class extensionPage extends javax.swing.JFrame {

    DataAbstract table = new DataAbstract("Submissions.txt");
    Student currentStudent;

    /**
     * Creates new form extensionPage
     */
    public extensionPage() {
        currentStudent = (Student) Student.getInstance();
        initComponents();
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        extensionBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        assessmentText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        extensionTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("REQUEST EXTENSION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 220, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECTED ASSESSMENT:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 20));

        jTextField2.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        extensionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        extensionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extensionBoxActionPerformed(evt);
            }
        });
        getContentPane().add(extensionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 350, -1));

        submitButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 240, 80));

        assessmentText.setEditable(false);
        assessmentText.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(assessmentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 350, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SELECT EXTENSION PERIOD:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        extensionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Assessment ID", "Extension status", "Extended Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        extensionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extensionTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extensionTableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(extensionTable);
        if (extensionTable.getColumnModel().getColumnCount() > 0) {
            extensionTable.getColumnModel().getColumn(0).setResizable(false);
            extensionTable.getColumnModel().getColumn(1).setResizable(false);
            extensionTable.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 880, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/student/img/pexels-anna-tarazevich-5936283.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table() {
        DefaultTableModel model = (DefaultTableModel) extensionTable.getModel();
        model.setRowCount(0);
        List<String[]> allRows = table.getAllRows();

        String currentStudentTP = currentStudent.getUserID();

        for (int i = 0; i < allRows.size(); i++) {
            String[] rowData = allRows.get(i);
            String[] newData = new String[]{rowData[0], rowData[11], rowData[12]};

            String[] studentTPs = rowData[1].split(",");
            boolean matchFound = false;
            for (String TP : studentTPs) {
                if (TP.trim().equals(currentStudentTP)) {
                    matchFound = true;
                    break;
                }
            }

            if (matchFound) {
                model.addRow(newData);
            }
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        studentPage home = new studentPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void extensionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extensionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extensionBoxActionPerformed

    private void extensionTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extensionTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_extensionTableMouseEntered

    private void extensionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extensionTableMouseClicked
        int selectedRow = extensionTable.getSelectedRow();
        if (selectedRow != -1) {
            String selectedAssessment = (String) extensionTable.getValueAt(selectedRow, 0);
            assessmentText.setText(selectedAssessment);
        }
    }//GEN-LAST:event_extensionTableMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        int selected = extensionTable.getSelectedRow();
        if (selected != -1) {
            DefaultTableModel model = (DefaultTableModel) extensionTable.getModel();
            String aftdays = extensionBox.getSelectedItem().toString();
            String assessmentID = (String) model.getValueAt(selected, 0); // Assessment ID

            try {
                DataAbstract db = new DataAbstract("Submission.txt");
                List<String[]> allRows = db.getAllRows();

                boolean updated = false;
                for (int i = 0; i < allRows.size(); i++) {
                    String[] parts = allRows.get(i);
                    if (parts[2].equals(assessmentID)) {
                        // Update the Request Extension days column (11th column) with the new value
                        parts[11] = aftdays;
                        if (db.updateRow(i + 1, parts)) { // Row index in DataAbstract is 1-based
                            updated = true;
                            break;
                        }
                    }
                }

                if (updated) {
                    Table(); // Refresh the table data
                    javax.swing.JOptionPane.showMessageDialog(null, "Data updated successfully.");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "An error occurred while updating data.");
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select a row to update.");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(extensionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(extensionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(extensionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(extensionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new extensionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assessmentText;
    private javax.swing.JComboBox<String> extensionBox;
    private javax.swing.JTable extensionTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
