/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.student;

import apu.y2s1.pms.DataAbstract;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import apu.y2s1.pms.User;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class presentationPage extends javax.swing.JFrame {

    DataAbstract table = new DataAbstract("Submissions.txt");
    Student currentStudent;

    /**
     * Creates new form presentationPage
     */
    public presentationPage() {
        currentStudent = (Student) Student.getInstance();
        initComponents();
        Table();
    }

    private void Table() {
        DefaultTableModel model = (DefaultTableModel) reqTable.getModel();
        model.setRowCount(0);
        List<String[]> allRows = table.getAllRows();

        String currentStudentTP = currentStudent.getUserID();

        for (int i = 0; i < allRows.size(); i++) {
            String[] rowData = allRows.get(i);
            String[] newData = new String[]{rowData[2], rowData[4], rowData[5]};

            String[] studentTPs = rowData[1].split(";");
            boolean matchFound = false;
            for (String TP : studentTPs) {
                if (TP.trim().equals(currentStudentTP)) {
                    matchFound = true;
                    break;
                }
            }

            if (matchFound) {
                model.addRow(newData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btHome = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        reqDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        assessmentText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reqTable = new javax.swing.JTable();
        presentationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REQUEST PRESENTATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        btHome.setBackground(new java.awt.Color(0, 102, 102));
        btHome.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btHome.setForeground(new java.awt.Color(0, 0, 0));
        btHome.setText("HOME");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));
        getContentPane().add(reqDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 320, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Assessment ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        assessmentText.setEditable(false);
        assessmentText.setBackground(new java.awt.Color(242, 242, 242));
        getContentPane().add(assessmentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 320, -1));

        reqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Assessment ID", "Presentation Date", "Slot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reqTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reqTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(reqTable);
        if (reqTable.getColumnModel().getColumnCount() > 0) {
            reqTable.getColumnModel().getColumn(0).setResizable(false);
            reqTable.getColumnModel().getColumn(1).setResizable(false);
            reqTable.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 570, 540));

        presentationButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        presentationButton.setText("SUBMIT");
        presentationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(presentationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 320, 60));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please select preferred day for presentation:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive - Asia Pacific University\\Desktop\\Object Oriented Development with Java\\pexels-anna-tarazevich-5936283.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        studentPage home = new studentPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void presentationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentationButtonActionPerformed
        int selectedRow = reqTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to submit presentation details.");
            return;
        }
        String selectedAssessment = (String) reqTable.getValueAt(selectedRow, 0);
        Date pptDate = reqDate.getDate();
        if (pptDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a presentation date.");
            return;
        }
        // Format the presentation date to dd/mm/yyyy
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String formattedPptDate = dateFormat.format(pptDate);

        try {
            List<String> lines = Files.readAllLines(Paths.get("Submissions.txt"), StandardCharsets.UTF_8);
            boolean updated = false;
            for (int i = 0; i < lines.size(); i++) {
                String[] parts = lines.get(i).split(";");
                if (parts[2].equals(selectedAssessment)) {
                    parts[4] = formattedPptDate;
                    lines.set(i, String.join(";", parts));
                    updated = true;
                    break;
                }
            }
            if (updated) {
                Files.write(Paths.get("Submissions.txt"), lines, StandardCharsets.UTF_8);
                JOptionPane.showMessageDialog(this, "Presentation details submitted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "An error occurred while updating data.");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_presentationButtonActionPerformed

    private void reqTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqTableMouseClicked
        int selectedRow = reqTable.getSelectedRow();
        if (selectedRow != -1) {
            String selectedAssessment = (String) reqTable.getValueAt(selectedRow, 0);
            assessmentText.setText(selectedAssessment);
        }
    }//GEN-LAST:event_reqTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presentationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assessmentText;
    private javax.swing.JButton btHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton presentationButton;
    private com.toedter.calendar.JDateChooser reqDate;
    private javax.swing.JTable reqTable;
    // End of variables declaration//GEN-END:variables
}
