/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.student;

import apu.y2s1.pms.DataAbstract;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import apu.y2s1.pms.User;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class presentationPage extends javax.swing.JFrame {

    DataAbstract table = new DataAbstract("Submissions.txt");
    User user = User.getInstance();

    /**
     * Creates new form presentationPage
     */
    public presentationPage() {
        initComponents();
        Table();
        reqTable.getTableHeader().setReorderingAllowed(false);
    }

    private void Table() {
        DefaultTableModel model = (DefaultTableModel) reqTable.getModel();
        model.setRowCount(0);
        List<String[]> allRows = table.getAllRows();

        String currentStudentTP = user.getUserID();

        for (int i = 1; i < allRows.size(); i++) {
            String[] rowData = allRows.get(i);
            String[] newData = new String[]{rowData[1], rowData[2], rowData[7], rowData[8]};

            String[] studentTPs = rowData[10].split(",");
            boolean matchFound = false;
            for (String TP : studentTPs) {
                if (TP.trim().equals(currentStudentTP)) {
                    matchFound = true;
                    break;
                }
            }

            if (matchFound) {
                model.addRow(newData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btHome = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textDate = new javax.swing.JTextField();
        btReq = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textTime = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reqTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REQUEST PRESENTATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        btHome.setBackground(new java.awt.Color(0, 102, 102));
        btHome.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btHome.setForeground(new java.awt.Color(0, 0, 0));
        btHome.setText("HOME");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        jLabel2.setText("ENTER PREFERRED DATE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        textDate.setBackground(new java.awt.Color(242, 242, 242));
        textDate.setForeground(new java.awt.Color(204, 204, 204));
        textDate.setText("DD/MM/YYYY");
        textDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDateFocusLost(evt);
            }
        });
        textDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateActionPerformed(evt);
            }
        });
        getContentPane().add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 350, -1));

        btReq.setBackground(new java.awt.Color(102, 102, 102));
        btReq.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btReq.setText("REQUEST");
        btReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReqActionPerformed(evt);
            }
        });
        getContentPane().add(btReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 370, 40));

        jLabel4.setText("ENTER PREFFERED TIME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        textTime.setBackground(new java.awt.Color(242, 242, 242));
        textTime.setForeground(new java.awt.Color(204, 204, 204));
        textTime.setText("00:00");
        textTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textTimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textTimeFocusLost(evt);
            }
        });
        textTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTimeActionPerformed(evt);
            }
        });
        getContentPane().add(textTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 350, -1));

        jTextField3.setBackground(new java.awt.Color(0, 153, 153));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 880, 170));

        reqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STATUS", "PRESENTATION DATE", "PRESENTATION TIME"
            }
        ));
        jScrollPane1.setViewportView(reqTable);
        if (reqTable.getColumnModel().getColumnCount() > 0) {
            reqTable.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 890, 360));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive - Asia Pacific University\\Desktop\\Object Oriented Development with Java\\pexels-anna-tarazevich-5936283.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        studentPage home = new studentPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHomeActionPerformed


    private void btReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btReqActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) reqTable.getModel();
        String[] add = {textDate.getText(), textTime.getText()};
        String currentStudentTP = user.getUserID();
        model.addRow(add);
        String filename = "Reports.txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename, true))) {
            String updateReport = ";" + ";" + ";" + ";" + ";" + ";"
                    + ";" + textDate.getText() + textTime.getText() + ";"
                    + currentStudentTP + ";";
            writer.write(updateReport);
            writer.newLine();
            JOptionPane.showMessageDialog(this, "User info updated successfully");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "User info updated unsuccessfully");
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void textDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateActionPerformed

    }//GEN-LAST:event_textDateActionPerformed

    private void textDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDateFocusGained
        if (textDate.getText().equals("DD/MM/YYYY")) {
            textDate.setText("");
            textDate.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textDateFocusGained

    private void textDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDateFocusLost
        if (textDate.getText().equals("")) {
            textDate.setText("DD/MM/YYYY");
            textDate.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textDateFocusLost

    private void textTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTimeActionPerformed

    private void textTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTimeFocusGained
        if (textTime.getText().equals("00:00")) {
            textTime.setText("");
            textTime.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textTimeFocusGained

    private void textTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTimeFocusLost
        if (textTime.getText().equals("")) {
            textTime.setText("00:00");
            textTime.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_textTimeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presentationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHome;
    private javax.swing.JButton btReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable reqTable;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textTime;
    // End of variables declaration//GEN-END:variables
}
