/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.student;

/**
 *
 * @author User
 */
public class studentPage extends javax.swing.JFrame {
    Student currentUser;

    /**
     * Creates new form login
     */
    public studentPage() {
        initComponents();
        currentUser = (Student) Student.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTsubmit = new javax.swing.JButton();
        BTrequest = new javax.swing.JButton();
        BTstatus = new javax.swing.JButton();
        BTlogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Student Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel2.setText("PLEASE SELECT AN ACTION YOU WANT TO CONTINUE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 429, -1));

        BTsubmit.setBackground(new java.awt.Color(255, 255, 255));
        BTsubmit.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BTsubmit.setForeground(new java.awt.Color(0, 0, 0));
        BTsubmit.setText("SUBMIT REPORT");
        BTsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(BTsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 210, 50));

        BTrequest.setBackground(new java.awt.Color(255, 255, 255));
        BTrequest.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BTrequest.setForeground(new java.awt.Color(0, 0, 0));
        BTrequest.setText("REQUEST PRESENTATION ");
        BTrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTrequestActionPerformed(evt);
            }
        });
        getContentPane().add(BTrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 210, 50));

        BTstatus.setBackground(new java.awt.Color(255, 255, 255));
        BTstatus.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BTstatus.setForeground(new java.awt.Color(0, 0, 0));
        BTstatus.setText("SUBMISSION STATUS");
        BTstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTstatusActionPerformed(evt);
            }
        });
        getContentPane().add(BTstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 210, 50));

        BTlogout.setBackground(new java.awt.Color(255, 255, 255));
        BTlogout.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BTlogout.setForeground(new java.awt.Color(0, 0, 0));
        BTlogout.setText("LOGOUT");
        BTlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(BTlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 210, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("REQUEST EXTENSION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 210, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("VIEW FEEDBACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 210, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive - Asia Pacific University\\Desktop\\Object Oriented Development with Java\\pexels-anna-tarazevich-5936283.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsubmitActionPerformed
        submitPage home = new submitPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTsubmitActionPerformed

    private void BTrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTrequestActionPerformed
        presentationPage home = new presentationPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTrequestActionPerformed

    private void BTstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTstatusActionPerformed
        statusPage home = new statusPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTstatusActionPerformed

    private void BTlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTlogoutActionPerformed
        apu.y2s1.pms.Login login = new apu.y2s1.pms.Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTlogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        extensionPage home = new extensionPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FeedbackPage home = new FeedbackPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTlogout;
    private javax.swing.JButton BTrequest;
    private javax.swing.JButton BTstatus;
    private javax.swing.JButton BTsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
