/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.student;

import apu.y2s1.pms.DataAbstract;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/**
 *
 * @author User
 */
public class submitPage extends javax.swing.JFrame {

    DataAbstract table = new DataAbstract("Students.txt");
    Student currentStudent;

    /**
     * Creates new form submitPage
     */
    public submitPage() {
        currentStudent = (Student) Student.getInstance();
        initComponents();
        Table();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void Table() {
        DefaultTableModel model = (DefaultTableModel) submitTable.getModel();
        model.setRowCount(0);
        String currentStudentTP = currentStudent.getUserID();
        DataAbstract studentData = new DataAbstract("Students.txt", ";");
        List<String[]> allStudents = studentData.getAllRows();
        for (String[] rowData : allStudents) {
            String[] studentTPs = rowData[0].split(";"); 
            boolean matchFound = false;
            String assessmentType = "";
            for (String TP : studentTPs) {
                if (TP.trim().equals(currentStudentTP)) {
                    matchFound = true;
                    assessmentType = rowData[5].trim();                    
                    break;
                }
            }
            if (matchFound) {
                DataAbstract assessmentData = new DataAbstract("Assessments.txt", ";");
                List<String[]> allAssessments = assessmentData.getAllRows();
                for (String[] aRow : allAssessments) {
                    if (aRow[2].trim().equals(assessmentType)) { 
                        String assessmentID = aRow[0].trim();   
                        String handOutDate = aRow[6].trim();     
                        String dueDate = aRow[7].trim();       
                        model.addRow(new String[]{assessmentID, handOutDate, dueDate});
                        break; 
                    }
                }
            }
        }

    }
    
    public class IDGenerator {
        private static final Random random = new Random();
        public String generateID(){
            int randomNumber = random.nextInt(900)+100;
            return "S" + randomNumber;
        }
    }
    
    
    
   

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BTsubmit = new javax.swing.JButton();
        BTedit = new javax.swing.JButton();
        BTdelete = new javax.swing.JButton();
        textDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        submitTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REPORT SUBMISSION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jTextField3.setBackground(new java.awt.Color(0, 102, 102));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        jLabel2.setText("Moodle Link:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        BTsubmit.setBackground(new java.awt.Color(102, 102, 102));
        BTsubmit.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BTsubmit.setText("SUBMIT");
        BTsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(BTsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 380, 40));

        BTedit.setBackground(new java.awt.Color(102, 102, 102));
        BTedit.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BTedit.setText("EDIT");
        BTedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTeditActionPerformed(evt);
            }
        });
        getContentPane().add(BTedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 190, 40));

        BTdelete.setBackground(new java.awt.Color(102, 102, 102));
        BTdelete.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BTdelete.setText("DELETE");
        getContentPane().add(BTdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 180, 40));

        textDate.setBackground(new java.awt.Color(242, 242, 242));
        textDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateActionPerformed(evt);
            }
        });
        getContentPane().add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, -1));

        submitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Assessment ID", "Hand Out Date", "Due Date"
            }
        ));
        jScrollPane1.setViewportView(submitTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 930, 430));

        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 930, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive - Asia Pacific University\\Desktop\\Object Oriented Development with Java\\pexels-anna-tarazevich-5936283.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void BTsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTsubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        studentPage home = new studentPage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTeditActionPerformed

    private void textDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(submitPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(submitPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(submitPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(submitPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new submitPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTdelete;
    private javax.swing.JButton BTedit;
    private javax.swing.JButton BTsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable submitTable;
    private javax.swing.JTextField textDate;
    // End of variables declaration//GEN-END:variables
}
