/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.pm;

import apu.y2s1.pms.DataAbstract;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeslyn
 */
public class PM_Assessment extends javax.swing.JFrame {
    DataAbstract table = new DataAbstract("Assessments.txt");
    DataAbstract combobox = new DataAbstract("Lecturers.txt");

    
    /**
     * Creates new form PM_Project
     */
    public PM_Assessment() {
        initComponents();
        ID.setEditable(false);
        ID.setFocusable(false);
        LoadData();
        Table();
    }
    
    private void LoadData() {
        for (int i = 2; i <= 10; i++) {
            String[] row = combobox.getRow(i);
            if (row != null && row.length > 1) {
                Supervisor.addItem(row[1]);
                FirstM.addItem(row[1]);
                SecondM.addItem(row[1]);
            }
        }
    }
    
    private void Table() {
        DefaultTableModel model = (DefaultTableModel) AssessmentTable.getModel();
        model.setRowCount(0);
        
        List<String[]> allRows = table.getAllRows();
        
        if (!allRows.isEmpty()) {
            String[] headers = allRows.get(0);
            model.setColumnIdentifiers(headers);
            
            for (int i = 1; i < allRows.size(); i++) {
                model.addRow(allRows.get(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssessmentTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Type = new javax.swing.JComboBox<>();
        Supervisor = new javax.swing.JComboBox<>();
        FirstM = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        SecondM = new javax.swing.JComboBox<>();
        Create = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("ASSESSMENT MANAGEMENT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        AssessmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AssessmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssessmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AssessmentTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 60, 400, 400));

        jLabel3.setText("Assessment Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Assessment Type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton1.setText("HOME");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        jLabel5.setText("Supervisor:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setText("First Marker:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Internship", "Investigation Report", "CP1", "CP2", "RMCP", "FYP" }));
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        getContentPane().add(Supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 80, -1));

        getContentPane().add(FirstM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 80, -1));

        jLabel7.setText("Second Marker:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        getContentPane().add(SecondM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 80, -1));

        Create.setText("CREATE");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        getContentPane().add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        Edit.setText("EDIT");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel8.setText("Assessment ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        String name = Name.getText();
        String type = Type.getSelectedItem().toString();
        String supervisor = Supervisor.getSelectedItem().toString();
        String fmarker = FirstM.getSelectedItem().toString();
        String smarker = SecondM.getSelectedItem().toString();
        String id = AssessmentID();
        
        String[] newData = {id, name, type, supervisor, fmarker, smarker};
        
        if (table.writeTo(newData)) {
            Table();
        } else {
            javax.swing.JOptionPane.showMessageDialog(null,"An error occured while writing to file.");
        }
    }//GEN-LAST:event_CreateActionPerformed

    private void AssessmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssessmentTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) AssessmentTable.getModel();
        int row = AssessmentTable.getSelectedRow();
        
        ID.setText(model.getValueAt(row, 0).toString());
        Name.setText(model.getValueAt(row,1).toString());
        Type.setSelectedItem(model.getValueAt(row, 2).toString());
        Supervisor.setSelectedItem(model.getValueAt(row, 3).toString());
        FirstM.setSelectedItem(model.getValueAt(row, 4).toString());
        SecondM.setSelectedItem(model.getValueAt(row,5).toString());
    }//GEN-LAST:event_AssessmentTableMouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        int selected = AssessmentTable.getSelectedRow();
        if (selected != -1) {
            String id = ID.getText();
            String name = Name.getText();
            String type = Type.getSelectedItem().toString();
            String supervisor = Supervisor.getSelectedItem().toString();
            String fmarker = FirstM.getSelectedItem().toString();
            String smarker = SecondM.getSelectedItem().toString();
            
            String[] update = {id, name, type, supervisor, fmarker, smarker};
            
            if (table.updateRow(selected, update)) {
                Table();
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "An error occured while updating data.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "An error occured while updating data.");
        }
    }//GEN-LAST:event_EditActionPerformed

    private String AssessmentID() {
        String id = "A" + String.format("%03d", (int)(Math.random() * 1000));
        
        return id;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_Assessment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AssessmentTable;
    private javax.swing.JButton Create;
    private javax.swing.JButton Edit;
    private javax.swing.JComboBox<String> FirstM;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox<String> SecondM;
    private javax.swing.JComboBox<String> Supervisor;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
