/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.pm;

import apu.y2s1.pms.DataAbstract;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jeslyn
 */
public class PM_Allotment extends javax.swing.JFrame {
    DataAbstract table = new DataAbstract("Students.txt");
    
    /**
     * Creates new form PM_Allotment
     */
    public PM_Allotment() {
        initComponents();
        Sort.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Table();
            }
    });
        LoadData();
        Table();
        AssessmentType();
    }
    
    private void LoadData() {
        for (int i = 1; i <= 20; i++) {
            String[] row = table.getRow(i);
            if (row != null && row.length > 1) {
                String[] data = new String[4];
                data[0] = (row.length > 0) ? row[0] : "";
                data[1] = (row.length > 1) ? row[1] : "";
                data[2] = (row.length > 4) ? row[4] : "";
                data[3] = (row.length > 5) ? row[5] : "";
                Sort.addItem(data[2]);
                Intake.addItem(data[2]);
            }
        }
    }
    
    private void Table() {
        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        model.setRowCount(0);
        
        String sort = (String) Sort.getSelectedItem();
        
        List<String[]> allRows = table.getAllRows();
        
        if (!allRows.isEmpty()) {
            for (String[] row : allRows) {
                if (row.length > 1) {
                    String[] data = new String[4];
                    data[0] = (row.length > 0) ? row[0] : "";
                    data[1] = (row.length > 1) ? row[1] : "";
                    data[2] = (row.length > 4) ? row[4] : "";
                    data[3] = (row.length > 5) ? row[5] : "";
                    if (sort.equals("All") || (!data[2].isEmpty() && data[2].equals(sort))) {
                        model.addRow(data);
                    }
                }
            }
        }
    }
    
    private void AssessmentType() {
        String intake = (String) Intake.getSelectedItem();
        Type.removeAllItems();

        if (intake.contains("APU3F") || intake.contains("APD3F")) {
            Type.addItem("Investigation Report");
            Type.addItem("FYP");
        } else if (intake.contains("APU2F") || intake.contains("APD2F")) {
            Type.addItem("Internship");
        } else if (intake.contains("FT-TT")) {
            Type.addItem("RMCP");
            Type.addItem("CP1");
            Type.addItem("CP2");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sort = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Search = new javax.swing.JTextField();
        Allot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        All = new javax.swing.JButton();
        Intake = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(255, 190, 152));
        Home.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel1.setBackground(new java.awt.Color(255, 190, 152));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENTS ALLOTMENT");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("Filter By:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        Sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        getContentPane().add(Sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setText("Search Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setText("Assessment Type:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel6.setText("Student Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel7.setText("Student Intake:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        Name.setFocusable(false);
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 150, -1));

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, -1));

        Allot.setFont(new java.awt.Font("Segoe Print", 1, 10)); // NOI18N
        Allot.setText("ALLOT");
        Allot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllotActionPerformed(evt);
            }
        });
        getContentPane().add(Allot, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TP Number", "Name", "Intake Code", "Assessment Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentTable);
        if (StudentTable.getColumnModel().getColumnCount() > 0) {
            StudentTable.getColumnModel().getColumn(0).setResizable(false);
            StudentTable.getColumnModel().getColumn(1).setResizable(false);
            StudentTable.getColumnModel().getColumn(2).setResizable(false);
            StudentTable.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 600, 480));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        ID.setFocusable(false);
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, -1));

        All.setFont(new java.awt.Font("Segoe Print", 1, 10)); // NOI18N
        All.setText("ALLOT ALL");
        All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllActionPerformed(evt);
            }
        });
        getContentPane().add(All, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        getContentPane().add(Intake, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 150, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/pm/img/Functionpage.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        DefaultTableModel table = (DefaultTableModel) StudentTable.getModel();
        TableRowSorter<DefaultTableModel> search = new TableRowSorter<>(table);
        StudentTable.setRowSorter(search);
        String field = Search.getText().toLowerCase();
        search.setRowFilter(RowFilter.regexFilter("(?i)" + field, 1));
    }//GEN-LAST:event_SearchActionPerformed

    private void AllotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllotActionPerformed
        int selected = StudentTable.getSelectedRow();
        
        if (selected != -1) { 
            DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
            String id = model.getValueAt(selected, 0).toString();
            String name = model.getValueAt(selected, 1).toString();
            String intake = Intake.getSelectedItem().toString();
            String type = Type.getSelectedItem().toString();
            
            String[] existed = table.getRow(selected + 1);
            
            String pwd = existed[2];
            String email = existed[3];
            
            String[] update = {id, name, pwd, email, intake, type};
            
            if (table.updateRow(selected, update)) {
                Table();
                javax.swing.JOptionPane.showMessageDialog(null, "The data has been updated successfully.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "An error occured while updating data.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "An error occured while updating data.");
        }
    }//GEN-LAST:event_AllotActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        PM_FunctionPage home = new PM_FunctionPage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        int row = StudentTable.getSelectedRow();
        
        ID.setText(model.getValueAt(row, 0).toString());
        Name.setText(model.getValueAt(row,1).toString());
        Intake.setSelectedItem(model.getValueAt(row, 2).toString());
        Type.setSelectedItem(model.getValueAt(row, 3).toString());
        
        AssessmentType();
    }//GEN-LAST:event_StudentTableMouseClicked

    private void AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllActionPerformed
        String intake = Intake.getSelectedItem().toString();
        String type = Type.getSelectedItem().toString();

        List<String[]> allRows = table.getAllRows();
        boolean update = false;

        if (!allRows.isEmpty()) {
            for (int i = 0; i < allRows.size(); i++) {
                String[] row = allRows.get(i);
                if (row.length > 4 && row[4].equals(intake)) {
                    row[5] = type;
                    if (table.updateRow(i, row)) {
                        Table();
                        update = true;
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(null, "An error occurred while updating assessment type.");
                    }
                }
                if (update)
                    break;
            }
            if (update)
                javax.swing.JOptionPane.showMessageDialog(null, "The data has been updated successfully.");
            else
                javax.swing.JOptionPane.showMessageDialog(null, "No matching data found to update.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "No data to update.");
        }
    }//GEN-LAST:event_AllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_Allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_Allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_Allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_Allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_Allotment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton All;
    private javax.swing.JButton Allot;
    private javax.swing.JButton Home;
    private javax.swing.JTextField ID;
    private javax.swing.JComboBox<String> Intake;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Search;
    private javax.swing.JComboBox<String> Sort;
    private javax.swing.JTable StudentTable;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
