/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.pm;

/**
 *
 * @author Jeslyn
 */
public class PM_FunctionPage extends javax.swing.JFrame {

    /**
     * Creates new form Lec_FunctionPage
     */
    public PM_FunctionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Project = new javax.swing.JButton();
        Allotment = new javax.swing.JButton();
        Feedback = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Calendar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel1.setText("FUNCTION PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 18)); // NOI18N
        jLabel2.setText("PLEASE SELECT AN ACTION YOU WANT TO CONTINUE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        Project.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        Project.setText("ASSESSMENT MANAGEMENT");
        Project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectActionPerformed(evt);
            }
        });
        getContentPane().add(Project, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 250, 50));

        Allotment.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        Allotment.setText("STUDENTS ALLOTMENT");
        Allotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllotmentActionPerformed(evt);
            }
        });
        getContentPane().add(Allotment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 250, 50));

        Feedback.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        Feedback.setText("GENERATE FEEDBACK REPORT");
        Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 250, 50));

        Report.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        Report.setText("REPORT STATUS");
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });
        getContentPane().add(Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 250, 50));

        Logout.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        Logout.setText("LOG OUT");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 250, 50));

        Calendar.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        Calendar.setText("EVENT CALENDAR");
        Calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalendarActionPerformed(evt);
            }
        });
        getContentPane().add(Calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 250, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/pm/Home.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectActionPerformed
        PM_Assessment project = new PM_Assessment();
        project.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProjectActionPerformed

    private void AllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllotmentActionPerformed
        PM_Allotment allotment = new PM_Allotment();
        allotment.setVisible(true);
        dispose();
    }//GEN-LAST:event_AllotmentActionPerformed

    private void FeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackActionPerformed
        PM_FeedbackReport feedback = new PM_FeedbackReport();
        feedback.setVisible(true);
        dispose();
    }//GEN-LAST:event_FeedbackActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        apu.y2s1.pms.Login login = new apu.y2s1.pms.Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void CalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalendarActionPerformed
        PM_Calendar calendar = new PM_Calendar();
        calendar.setVisible(true);
        dispose();
    }//GEN-LAST:event_CalendarActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        PM_ReportStatus report = new PM_ReportStatus();
        report.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_FunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_FunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_FunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_FunctionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_FunctionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Allotment;
    private javax.swing.JButton Calendar;
    private javax.swing.JButton Feedback;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Project;
    private javax.swing.JButton Report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
