/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.y2s1.pms.pm;

import apu.y2s1.pms.DataAbstract;
import java.awt.print.PrinterException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeslyn
 */
public class PM_FeedbackReport extends javax.swing.JFrame {
    DataAbstract table = new DataAbstract("Submissions.txt");

    /**
     * Creates new form PM_FeedbackReport
     */
    public PM_FeedbackReport() {
        initComponents();
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Report = new javax.swing.JTextArea();
        Print = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(255, 190, 152));
        Home.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel1.setBackground(new java.awt.Color(255, 190, 152));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GENERATE FEEDBACK REPORT");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Submission ID", "Student ID", "Assessment ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReportTable);
        if (ReportTable.getColumnModel().getColumnCount() > 0) {
            ReportTable.getColumnModel().getColumn(0).setResizable(false);
            ReportTable.getColumnModel().getColumn(2).setResizable(false);
            ReportTable.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 480, 440));

        Report.setEditable(false);
        Report.setColumns(20);
        Report.setRows(5);
        Report.setFocusable(false);
        jScrollPane2.setViewportView(Report);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 370, 490));

        Print.setText("PRINT");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        getContentPane().add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu/y2s1/pms/pm/img/Functionpage.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Table() {
        DefaultTableModel model = (DefaultTableModel) ReportTable.getModel();
        model.setRowCount(0);
        
        List<String[]> allRows = table.getAllRows();
        
        if (!allRows.isEmpty()) {
            for (String[] row : allRows) {
                if (row.length > 1) {
                    String[] data = new String[4];
                    data[0] = (row.length > 0) ? row[0] : "";
                    data[1] = (row.length > 1) ? row[1] : "";
                    data[2] = (row.length > 2) ? row[2] : "";
                    data[3] = (row.length > 6) ? row[6] : "";
                    if (data[3].equals("Graded")) {
                        model.addRow(data);
                    }
                }
            }
        }
    }
    
    
    
    private String[] getFullData(String submissionId) {
        List<String[]> allRows = table.getAllRows();
        for (String[] row : allRows) {
            if (row.length > 0 && row[0].equals(submissionId)) {
                return row;
            }
        }
        return new String[0];
    }
    
    private void displayFullData(String submissionId) {
        String[] data = getFullData(submissionId);
        if (data.length > 0) {
            Report.setText("");
            Report.append("                      APU PROJECT MANAGEMENT SYSTEM                \n");
            Report.append("      -----------------------------------------------------------------------------\n");
            Report.append("                                     FEEDBACK REPORT                    \n");
            Report.append("      -----------------------------------------------------------------------------\n");
            Report.append("\n Submission ID: " + data[0] + "\n");
            Report.append("\n Student ID: " + data[1] + "\n");
            Report.append("\n Assessment ID: " + data[2] + "\n");
            Report.append("\n Submission Date: " + data[3] + "\n");
            Report.append("\n Presentation DateTime: " + data[4] + "\n");
            Report.append("\n Status: " + data[6] + "\n");
            Report.append("\n Result: " + data[7] + "\n");
            Report.append("\n Feedback: " + data[8] + "\n");
            Report.append("\n 1st marker Comment: " + data[9] + "\n");
            Report.append("\n 2nd marker Comment: " + data[10] + "\n");
            Report.append("\n Request Extension: " + data[11] + "\n");
            Report.append("\n New Submission Date: " + data[12]);
        }
    }
    
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        PM_FunctionPage home = new PM_FunctionPage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            Report.print();
        } catch (PrinterException ex){
            JOptionPane.showMessageDialog(null, "An error occurred.");
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void ReportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportTableMouseClicked
        int selectedRow = ReportTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) ReportTable.getModel();
            String submissionId = (String) model.getValueAt(selectedRow, 0);
            displayFullData(submissionId);
        }
    }//GEN-LAST:event_ReportTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_FeedbackReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_FeedbackReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_FeedbackReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_FeedbackReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_FeedbackReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton Print;
    private javax.swing.JTextArea Report;
    private javax.swing.JTable ReportTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
